# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ScreenRegister(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("banco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 80))
        self.frame.setStyleSheet("background-color: rgb(0, 55, 104);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(239, 10, 322, 60))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-10, 80, 800, 520))
        self.frame_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame_2.setStyleSheet("background-color: rgb(211, 243, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEditRegisterName = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterName.setGeometry(QtCore.QRect(60, 130, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterName.setFont(font)
        self.lineEditRegisterName.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterName.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterName.setMaxLength(40)
        self.lineEditRegisterName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditRegisterName.setDragEnabled(False)
        self.lineEditRegisterName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterName.setClearButtonEnabled(False)
        self.lineEditRegisterName.setObjectName("lineEditRegisterName")
        self.lineEditRegisterSurname = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterSurname.setGeometry(QtCore.QRect(60, 180, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterSurname.setFont(font)
        self.lineEditRegisterSurname.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterSurname.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterSurname.setInputMethodHints(QtCore.Qt.ImhDate)
        self.lineEditRegisterSurname.setMaxLength(11)
        self.lineEditRegisterSurname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditRegisterSurname.setDragEnabled(False)
        self.lineEditRegisterSurname.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterSurname.setClearButtonEnabled(False)
        self.lineEditRegisterSurname.setObjectName("lineEditRegisterSurname")
        self.pushButtonRegister = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonRegister.setGeometry(QtCore.QRect(350, 380, 100, 36))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRegister.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(134, 127, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.pushButtonComeBack = QtWidgets.QPushButton(self.frame_2)
        self.pushButtonComeBack.setGeometry(QtCore.QRect(345, 436, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonComeBack.setFont(font)
        self.pushButtonComeBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonComeBack.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:rgb(134, 127, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButtonComeBack.setObjectName("pushButtonComeBack")
        self.lineEditRegisterCPF = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterCPF.setGeometry(QtCore.QRect(60, 230, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterCPF.setFont(font)
        self.lineEditRegisterCPF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterCPF.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterCPF.setMaxLength(11)
        self.lineEditRegisterCPF.setDragEnabled(False)
        self.lineEditRegisterCPF.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterCPF.setClearButtonEnabled(False)
        self.lineEditRegisterCPF.setObjectName("lineEditRegisterCPF")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 300, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 55, 104);\n"
"border: 0;\n"
"border-radius: 5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(450, 60, 300, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 55, 104);\n"
"border: 0;\n"
"border-radius: 5px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEditRegisterAccountNumber = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterAccountNumber.setGeometry(QtCore.QRect(470, 130, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterAccountNumber.setFont(font)
        self.lineEditRegisterAccountNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterAccountNumber.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterAccountNumber.setText("")
        self.lineEditRegisterAccountNumber.setMaxLength(40)
        self.lineEditRegisterAccountNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditRegisterAccountNumber.setDragEnabled(False)
        self.lineEditRegisterAccountNumber.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterAccountNumber.setClearButtonEnabled(False)
        self.lineEditRegisterAccountNumber.setObjectName("lineEditRegisterAccountNumber")
        self.lineEditRegisterAccountPassword = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterAccountPassword.setGeometry(QtCore.QRect(470, 230, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterAccountPassword.setFont(font)
        self.lineEditRegisterAccountPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterAccountPassword.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterAccountPassword.setText("")
        self.lineEditRegisterAccountPassword.setMaxLength(40)
        self.lineEditRegisterAccountPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditRegisterAccountPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditRegisterAccountPassword.setDragEnabled(False)
        self.lineEditRegisterAccountPassword.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterAccountPassword.setClearButtonEnabled(False)
        self.lineEditRegisterAccountPassword.setObjectName("lineEditRegisterAccountPassword")
        self.lineEditRegisterAccountBalance = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditRegisterAccountBalance.setGeometry(QtCore.QRect(470, 180, 260, 42))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRegisterAccountBalance.setFont(font)
        self.lineEditRegisterAccountBalance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineEditRegisterAccountBalance.setStyleSheet("QLineEdit {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 55, 104);\n"
"    border: 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.lineEditRegisterAccountBalance.setText("")
        self.lineEditRegisterAccountBalance.setMaxLength(40)
        self.lineEditRegisterAccountBalance.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditRegisterAccountBalance.setDragEnabled(False)
        self.lineEditRegisterAccountBalance.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEditRegisterAccountBalance.setClearButtonEnabled(False)
        self.lineEditRegisterAccountBalance.setObjectName("lineEditRegisterAccountBalance")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditRegisterName, self.lineEditRegisterSurname)
        MainWindow.setTabOrder(self.lineEditRegisterSurname, self.lineEditRegisterCPF)
        MainWindow.setTabOrder(self.lineEditRegisterCPF, self.lineEditRegisterAccountNumber)
        MainWindow.setTabOrder(self.lineEditRegisterAccountNumber, self.lineEditRegisterAccountBalance)
        MainWindow.setTabOrder(self.lineEditRegisterAccountBalance, self.lineEditRegisterAccountPassword)
        MainWindow.setTabOrder(self.lineEditRegisterAccountPassword, self.pushButtonRegister)
        MainWindow.setTabOrder(self.pushButtonRegister, self.pushButtonComeBack)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro"))
        self.label.setText(_translate("MainWindow", "Evollutte Bank"))
        self.lineEditRegisterName.setPlaceholderText(_translate("MainWindow", "Nome"))
        self.lineEditRegisterSurname.setPlaceholderText(_translate("MainWindow", "Sobrenome"))
        self.pushButtonRegister.setText(_translate("MainWindow", "Criar"))
        self.pushButtonComeBack.setText(_translate("MainWindow", "Voltar"))
        self.lineEditRegisterCPF.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.label_2.setText(_translate("MainWindow", "Dados Pessoais"))
        self.label_3.setText(_translate("MainWindow", "Dados Bancários"))
        self.lineEditRegisterAccountNumber.setPlaceholderText(_translate("MainWindow", "Conta"))
        self.lineEditRegisterAccountPassword.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.lineEditRegisterAccountBalance.setPlaceholderText(_translate("MainWindow", "Saldo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ScreenRegister()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
